### ISSUE TITLE
redshift_grant resource does not support granting privileges to users

### ISSUE THREAD

**Issue by viktorradnai** [brainly/terraform-provider-redshift#23]
The `redshift_grant` resource (https://registry.terraform.io/providers/brainly/redshift/latest/docs/resources/grant) currently only supports grants to groups, even though the equivalent native Redshift GRANT statement (https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html) supports both groups and users.

**Comment by viktorradnai** [comment]
I've created a test case that will show a permanent diff even if running `terraform apply` multiple times: https://gist.github.com/viktorradnai/3873bf5ccc9e6cb08fe3eed9e231a2df

This needs a provider config to run, eg: 
```
locals {
  db_host = "your-cluster.redshift.amazonaws.com"
  db_port = "5439"
  db_name = "your-db"

  db_superuser_name = "your-username"
  db_superuser_password = "your-password"
}

terraform {
  required_version = ">= 1.0.4"
  required_providers {
    redshift = {
      source  = "brainly/redshift"
      version = ">= 0.3.0"
    }
  }
}

provider "redshift" {
  database = local.db_name
  host     = local.db_host
  port     = local.db_port

  username = local.db_superuser_name
  password = local.db_superuser_password
}
```

**Comment by piyush-daga** [comment]
Hi, just wanted to know if there's a timeline for this enhancement? Thanks.

**Comment by winglot** [comment]
Hi sorry for the late reply. We have this in our backlog but currently no ETA. We manage users by organizing them in groups and assigning privileges to groups rather than individuals. That's why this currently has low priority.

If anyone wants to work on this in the future, please share the information here so we do not duplicate the work (in case I start working on that too).
