### ISSUE TITLE
can not set a user password to an md5 string, because it will be re-hashed

### ISSUE THREAD

**Issue by mtesch-um** [brainly/terraform-provider-redshift#97]
This used to work, but has been broken by always hashing the password string before sending it to CREATE USER.

There are now two PRs to fix this - I did the second one because I forgot there was already one:

https://github.com/brainly/terraform-provider-redshift/pull/90

https://github.com/brainly/terraform-provider-redshift/pull/96

**Comment by sworisbreathing** [comment]
@hoxu it probably should be configurable rather than forcing any of the options. I think I made the original PR to go with md5 because I was concerned about a) passwords being written in plaintext to query logs, and b) plaintext passwords being stored in general.

I probably would have used sha256 instead of md5 had I been aware that redshift supported it at the time. I was never a big fan of md5 but it seemed better than nothing.

Unfortunately I can't accept any PRs. I'm not a maintainer on this project, only a contributor like yourself.

**Comment by mtesch-um** [comment]
I would guess the reason to hash is to keep the unhashed password from passing over the wire unencrypted - probably a minor concern for most users, since the connection should be SSL anyhow.

> I probably would have used sha256 instead of md5 had I been aware that redshift

I dug into using sha256 at one point - if I'm remembering correctly, sha256 is only accepted for CREATE USER and not for ALTER USER.

**Comment by mtesch-um** [comment]
fwiw, my vote is for solution 1.
